version: '3'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
